name: Ben Pigao
favicon: null
layout_spectrum: 0.8782391070853919
typography_spectrum: 0.1567081247922033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7658398339990526
  lightness: 0.21285871509462595
  saturation: 0.5274614526424557
  rhythmicContrast: 0.16346008237451315
purpose: []
