name: Ben Pigao
favicon: null
layout_spectrum: 0.8782391070853919
typography_spectrum: 0.1567081247922033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9ceca'
    - '#141e27'
    - '#a2a8a6'
    - '#878c88'
    - '#3d4144'
  brandStrength: 0.8125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
